export default {
  CONNECT: 'SocketEvents.CONNECT',
  AUTHENTICATED: 'SocketEvents.AUTHENTICATED',
  FAILED_AUTH: 'SocketEvents.FAILED_AUTH',
  ADD_SERVER: 'SocketEvents.ADD_SERVER',
  ADDED_SERVER: 'SocketEvents.ADDED_SERVER',
  GLOBAL_ADDED_SERVER: 'SocketEvents.GLOBAL_ADDED_SERVER',
  TEST_SERVER: 'SocketEvents.TEST_SERVER',
  FAILED_ADDING_SERVER: 'SocketEvents.FAILED_ADDING_SERVER',
  SERVER_TEST_SUCCESS: 'SocketEvents.SERVER_TEST_SUCCESS',
  SERVER_TEST_FAILED: 'SocketEvents.SERVER_TEST_FAILED',

  DISCONNECT: 'disconnect',
  CONNECTION: 'connection'
};
